01/23/2025 17:15:17 - INFO - __main__ - ***** Running training *****
01/23/2025 17:15:17 - INFO - __main__ -   Num examples = 90092
01/23/2025 17:15:17 - INFO - __main__ -   Num batches each epoch = 704
01/23/2025 17:15:17 - INFO - __main__ -   Num Epochs = 114
01/23/2025 17:15:17 - INFO - __main__ -   Instantaneous batch size per device = 64
01/23/2025 17:15:17 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 128
01/23/2025 17:15:17 - INFO - __main__ -   Gradient Accumulation steps = 1
01/23/2025 17:15:17 - INFO - __main__ -   Total optimization steps = 80000
01/23/2025 17:15:17 - INFO - __main__ -  do_classifier_free_guidance = True
01/23/2025 17:15:17 - INFO - __main__ -  conditioning_dropout_prob = 0.05
Checkpoint 'latest' does not exist. Starting a new training run.
Steps:   0%|                                                                                                                                           | 0/80000 [00:00<?, ?it/s]/share/phoenix/nfs02/S6/localdisk/hj453/.conda/envs/neural-gaffer/lib/python3.9/site-packages/torch/utils/checkpoint.py:1399: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with device_autocast_ctx, torch.cpu.amp.autocast(**cpu_autocast_kwargs), recompute_context:  # type: ignore[attr-defined]
Steps:   0%|                                                                                                                               | 1/80000 [00:08<193:20:41,  8.70s/it]01/23/2025 17:15:29 - INFO - __main__ - Running unseen_object_with_random_light_condition validation...
cc_projection/diffusion_pytorch_model.safetensors not found
The config attributes {'cc_projection': ['pipeline_zero1to3', 'CCProjection']} were passed to Neural_Gaffer_StableDiffusionPipeline, but are not expected and will be ignored. Please verify your model_index.json configuration file.
Keyword arguments {'cc_projection': ['pipeline_zero1to3', 'CCProjection']} are not expected by Neural_Gaffer_StableDiffusionPipeline and will be ignored.
                  /share/phoenix/nfs02/S6/localdisk/hj453/code/Neural_Gaffer/neural_gaffer_training.py:131: FutureWarning: The input object of type 'Image' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Image', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  prediction_image_sample0 = np.array([cur_predicted_images[0][i] for i in range(batchsize)], dtype=np.float32) / 255.0
0it [00:04, ?it/s]
Traceback (most recent call last):
  File "/share/phoenix/nfs02/S6/localdisk/hj453/code/Neural_Gaffer/neural_gaffer_training.py", line 1262, in <module>
    main(args)
  File "/share/phoenix/nfs02/S6/localdisk/hj453/code/Neural_Gaffer/neural_gaffer_training.py", line 1104, in main
    image_logs, temp_log = log_validation(
  File "/share/phoenix/nfs02/S6/localdisk/hj453/code/Neural_Gaffer/neural_gaffer_training.py", line 131, in log_validation
    prediction_image_sample0 = np.array([cur_predicted_images[0][i] for i in range(batchsize)], dtype=np.float32) / 255.0
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/share/phoenix/nfs02/S6/localdisk/hj453/code/Neural_Gaffer/neural_gaffer_training.py", line 1262, in <module>
[rank0]:     main(args)
[rank0]:   File "/share/phoenix/nfs02/S6/localdisk/hj453/code/Neural_Gaffer/neural_gaffer_training.py", line 1104, in main
[rank0]:     image_logs, temp_log = log_validation(
[rank0]:   File "/share/phoenix/nfs02/S6/localdisk/hj453/code/Neural_Gaffer/neural_gaffer_training.py", line 131, in log_validation
[rank0]:     prediction_image_sample0 = np.array([cur_predicted_images[0][i] for i in range(batchsize)], dtype=np.float32) / 255.0
[rank0]: ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
